name: hedera_proof
description: "Decentralized NFT receipt system dashboard"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  google_fonts:
  mobile_scanner: ^4.0.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.19.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  path_provider: ^2.1.1
  share_plus: ^12.0.1
 




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/Screenshot 2025-11-25 104353.png
